name: Run Node.js Script

on:
  workflow_dispatch:  # Allows manual start

jobs:
  run-node:
    runs-on: ubuntu-latest  # Free GitHub runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Choose Node.js version

      - name: Install Dependencies
        run: npm install  # If you have a package.json

      - name: Run Node.js Script
        run: node app.js
